name: Spell Check

permissions: {}

on: [pull_request]

jobs:
  typos-check:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the JuliaLang/julia repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Check spelling
        uses: crate-ci/typos@master
  codespell:
    # https://github.com/codespell-project/codespell
    # This is a catch-all job to cover file extensions that aren't in another job
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: pip install codespell
      - run: codespell --skip='*.c,*.cpp,*.jl,*.md,*.rtf,*.scm,*.toml,*.S' --ignore-words=.codespell.ignore
  codespell-file-extension:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        file-extension:
          - 'c' # C files
          - 'cpp' # C++ files
          - 'jl' # Julia files
          - 'md' # Markdown files
          - 'rtf' # RTF (Rich Text Format) files
          - 'scm' # Scheme (femtolisp) files
          - 'toml' # TOML files
          - 'S' # Assembly language files
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: pip install codespell
      - run: find . -type f -name '*.${{ matrix.file-extension }}' -exec codespell --ignore-words=.codespell.jl.ignore {} \;
