name: Spell Check

permissions: {}

on: [pull_request]

jobs:
  typos-check:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the JuliaLang/julia repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Check spelling
        uses: crate-ci/typos@master
  codespell:
    # https://github.com/codespell-project/codespell
    # This is a catch-all job to cover file extensions that aren't in another job
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: pip install codespell
      - run: codespell --skip='*.jl,*.md,*.S' --ignore-words=.codespell.ignore
  codespell-jl:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: pip install codespell
      # Only Julia files (*.jl)
      - run: find . -type f -name '*.S' -exec codespell --ignore-words=.codespell.jl.ignore {} \;
  codespell-md:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: pip install codespell
      # Only Markdown files (*.md)
      - run: find . -type f -name '*.S' -exec codespell --ignore-words=.codespell.md.ignore {} \;
  codespell-asm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: pip install codespell
      # Only assembly files (*.S)
      - run: find . -type f -name '*.S' -exec codespell --ignore-words=.codespell.asm.ignore {} \;
