name: Spell Check

permissions: {}

on: [pull_request]

jobs:
  typos-check:
    name: Spell Check with Typos
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout the JuliaLang/julia repository
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Check spelling
        uses: crate-ci/typos@master
  codespell:
    # https://github.com/codespell-project/codespell
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: pip install codespell
      # All files except assembly files (*.S)
      - run: codespell --skip='*.S' --ignore-words=.codespell.ignore
  codespell-asm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - run: pip install codespell
      # Only assembly files
      - run: codespell --skip='*.c,*.cpp,*.jl,*.md,*.scm' --ignore-words=.codespell.asm.ignore
